/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package form;
import java.awt.Dimension;
import java.awt.Rectangle;
import java.awt.event.KeyEvent; 
import java.sql.Connection; 
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.Koneksi;
import java.text.SimpleDateFormat;


/**
 *
 * @author M ARIF MARTADINATA
 */
public class AbsensiPegawai extends javax.swing.JDialog {
    DefaultTableModel model = new DefaultTableModel();

    /**
     * Creates new form AbsensiPegawai
     */
    public AbsensiPegawai(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         Koneksi.koneksi();
         headerTable();
         tampilData ();
         bersih();
         tombol(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1_Nip = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2_Nama = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField3_Jabatan = new javax.swing.JTextField();
        jTextField4_Alamat = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5_Cari = new javax.swing.JButton();
        jButton1_Baru = new javax.swing.JButton();
        jButton2_Simpan = new javax.swing.JButton();
        jButton3_Hapus = new javax.swing.JButton();
        jButton4_Cetak = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        waktu = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Nama         :   ");

        jLabel3.setText("Jabatan       : ");

        jLabel4.setText("Alamat        : ");

        jTextField1_Nip.setText("Masukan NIP Anda");

        jLabel5.setText("Keterangan : ");

        jTextField2_Nama.setText("Masukan Nama Anda");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Keterangan", "Hadir", "Izin", "Tanpa Keterangan" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextField3_Jabatan.setText("Masukan Jabatan Anda");
        jTextField3_Jabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3_JabatanActionPerformed(evt);
            }
        });

        jTextField4_Alamat.setText("Masukan Alamat Anda");
        jTextField4_Alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4_AlamatActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("Title 1");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("Title 2");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("Title 3");
            jTable1.getColumnModel().getColumn(3).setHeaderValue("Title 4");
        }

        jButton5_Cari.setText("....");
        jButton5_Cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5_CariActionPerformed(evt);
            }
        });

        jButton1_Baru.setText("Baru");
        jButton1_Baru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_BaruActionPerformed(evt);
            }
        });

        jButton2_Simpan.setText("Simpan");
        jButton2_Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_SimpanActionPerformed(evt);
            }
        });

        jButton3_Hapus.setText("Hapus");
        jButton3_Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_HapusActionPerformed(evt);
            }
        });

        jButton4_Cetak.setText("Cetak");
        jButton4_Cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_CetakActionPerformed(evt);
            }
        });

        jLabel6.setText("NIP             : ");

        jLabel7.setText("Waktu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(63, 63, 63))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(7, 7, 7)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jButton5_Cari, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField2_Nama)
                                            .addComponent(jTextField1_Nip))
                                        .addGap(63, 63, 63))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField3_Jabatan))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(waktu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(67, 67, 67)))
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField4_Alamat)
                        .addGap(108, 108, 108))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1_Baru)
                        .addGap(41, 41, 41)
                        .addComponent(jButton2_Simpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(56, 56, 56)
                        .addComponent(jButton4_Cetak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(62, 62, 62)
                        .addComponent(jButton3_Hapus)
                        .addGap(870, 870, 870))))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButton5_Cari)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTextField1_Nip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTextField2_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTextField4_Alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTextField3_Jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(waktu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1)
                    .addComponent(jLabel5))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_Baru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2_Simpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4_Cetak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3_Hapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(372, 372, 372))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3_JabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3_JabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3_JabatanActionPerformed

    private void jButton5_CariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5_CariActionPerformed
        // TODO add your handling code here:
        CariPegawai objekCari = new CariPegawai(null, rootPaneCheckingEnabled);
        objekCari.setVisible(true);
    }//GEN-LAST:event_jButton5_CariActionPerformed

    private void jButton2_SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_SimpanActionPerformed
        // TODO add your handling code here:
        try {
            //String textFieldValue = waktu.getText();
            java.util.Date dateValue = waktu.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String formattedDate = sdf.format(dateValue);
            koneksi.Koneksi.st.executeUpdate("INSERT INTO tbl_absensi VALUES ('" +
                jTextField1_Nip.getText() + "','" +
                jTextField2_Nama.getText() + "','" +
                jTextField4_Alamat.getText() + "','" +
                jTextField3_Jabatan.getText() + "','" +
                formattedDate + "','" +
                jComboBox1.getSelectedItem() + "')");            
            JOptionPane.showMessageDialog(null, "Berhasil menyimpan");
            tampilPengguna();
            tombol(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "eror Simpan : "+e);
        }//blok catch
        
    }//GEN-LAST:event_jButton2_SimpanActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if(jTable1.getSelectedColumnCount()==0){
           int row = jTable1.getSelectedRow();
            jTextField1_Nip.setText(jTable1.getValueAt(row, 0).toString());
            jTextField2_Nama.setText(jTable1.getValueAt(row, 1).toString());
            jTextField4_Alamat.setText(jTable1.getValueAt(row, 2).toString());
            jTextField3_Jabatan.setText(jTable1.getValueAt(row, 3).toString());
            String dateString = jTable1.getValueAt(row, 4).toString();
            jComboBox1.setSelectedItem(jTable1.getValueAt(row, 5).toString());
            tombol(true);
        }//blok mause cliked
        

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3_HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_HapusActionPerformed
        // TODO add your handling code here:
          try {
            koneksi.Koneksi.st.executeUpdate("delete from tbl_absensi where nip = '"+jTextField1_Nip.getText()+"' "); 
            JOptionPane.showMessageDialog(null, "Berhasil menghapus");
            tampilData();
            tombol(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "eror Hapus : "+e);
        }//blok catch
                     
    }//GEN-LAST:event_jButton3_HapusActionPerformed

    private void jButton1_BaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_BaruActionPerformed
        // TODO add your handling code here:
        tombol(true);
        bersih();
    }//GEN-LAST:event_jButton1_BaruActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField4_AlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4_AlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4_AlamatActionPerformed

    private void jButton4_CetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_CetakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4_CetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AbsensiPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AbsensiPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AbsensiPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AbsensiPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AbsensiPegawai dialog = new AbsensiPegawai(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_Baru;
    private javax.swing.JButton jButton2_Simpan;
    private javax.swing.JButton jButton3_Hapus;
    private javax.swing.JButton jButton4_Cetak;
    private javax.swing.JButton jButton5_Cari;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    public static javax.swing.JTextField jTextField1_Nip;
    public static javax.swing.JTextField jTextField2_Nama;
    public static javax.swing.JTextField jTextField3_Jabatan;
    public static javax.swing.JTextField jTextField4_Alamat;
    private com.toedter.calendar.JDateChooser waktu;
    // End of variables declaration//GEN-END:variables
    void bersih(){
        
        jTextField1_Nip.setText("");
        jTextField2_Nama.setText(""); 
        jTextField3_Jabatan.setText("");
        jTextField4_Alamat.setText("");
        jComboBox1.setSelectedItem("");
        
    
    }
    private void headerTable(){
        model = new DefaultTableModel();
        model.addColumn("NIP");
        model.addColumn("Nama");
        model.addColumn("Alamat");
        model.addColumn("Jabatan"); 
        model.addColumn("Waktu"); 
        model.addColumn("Keterangan"); 
        jTable1.setModel(model);
    }//ini tag header
    public void tampilData (){
        model.getDataVector().removeAllElements();
        try {
            ResultSet rs=koneksi.Koneksi.st.executeQuery("SELECT * from view_absensi");
            while(rs.next()){
                Object[] data = new Object[7];
                data[0]=(rs.getString(1));
                data[1]=(rs.getString(2));
                data[2]=(rs.getString(3));
                data[3]=(rs.getString(4));
                data[4]=(rs.getString(5));
                data[5]=(rs.getString(6));
                
              
                model.addRow(data);
            }//ini tag while 
        } catch (Exception e) { 
            JOptionPane.showMessageDialog(null,"eror tampil : "+ e);
        } //ini tag catch
        bersih();
    }
    void tombol(boolean status){
        jButton1_Baru.setEnabled(true);
        jButton2_Simpan.setEnabled(status);
        jButton3_Hapus.setEnabled(status);
        jButton4_Cetak.setEnabled(status);
        jButton5_Cari.setEnabled(status);
 }//blok tombol
public void tampilPengguna(){
        model.getDataVector().removeAllElements();
        try {
            ResultSet rs=koneksi.Koneksi.st.executeQuery("select * from tbl_absensi");
            while(rs.next()){
                Object[] data = new Object[7];
                data[0]=(rs.getString(1));
                data[1]=(rs.getString(2));
                data[2]=(rs.getString(3));
                data[3]=(rs.getString(4)); 
                data[4]=(rs.getString(5)); 
                data[5]=(rs.getString(6)); 
               
                
                
                model.addRow(data);
            }//ini blok while 
        } catch (Exception e) { 
            JOptionPane.showMessageDialog(null,"eror tampil : "+ e);
        } //ini blok catch
        bersih();
    }//blok tampil
}
