/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package form;
import java.awt.Dimension;
import java.awt.Rectangle;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author M ARIF MARTADINATA
 */
public class Pegawai extends javax.swing.JDialog {
     DefaultTableModel model = new DefaultTableModel();

    public Pegawai(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        koneksi.Koneksi.koneksi();
        headerTable(); 
        tampilPengguna();
        tombol(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1_Nip = new javax.swing.JTextField();
        jTextField2_Nama = new javax.swing.JTextField();
        jTextField3_JenisKelamin = new javax.swing.JTextField();
        jTextField4_Ttl = new javax.swing.JTextField();
        jTextField5_Alamat = new javax.swing.JTextField();
        jTextField6_Telf = new javax.swing.JTextField();
        jButton1_Baru = new javax.swing.JButton();
        jButton2_Simpan = new javax.swing.JButton();
        jButton3_Ubah = new javax.swing.JButton();
        jButton4_Hapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("NIP : ");

        jLabel2.setText("Nama  :");

        jLabel3.setText("Jenis Kelamin :");

        jLabel4.setText("Tempat Tanggal Lahir : ");

        jLabel5.setText("Alamat   : ");

        jLabel6.setText("No. Telf  : ");

        jTextField1_Nip.setText("Masukan NIP Anda");
        jTextField1_Nip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_NipActionPerformed(evt);
            }
        });

        jTextField2_Nama.setText("Masukan Nama Anda");
        jTextField2_Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2_NamaActionPerformed(evt);
            }
        });

        jTextField3_JenisKelamin.setText("Masukan Jenis Kelamin Anda");
        jTextField3_JenisKelamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3_JenisKelaminActionPerformed(evt);
            }
        });

        jTextField4_Ttl.setText("Masukan Tempat Tanggal Lahir Anda");
        jTextField4_Ttl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4_TtlActionPerformed(evt);
            }
        });

        jTextField5_Alamat.setText("Masukan Alamat Anda");

        jTextField6_Telf.setText("Masukan No Telf Anda");

        jButton1_Baru.setText("Baru");
        jButton1_Baru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_BaruActionPerformed(evt);
            }
        });

        jButton2_Simpan.setText("Simpan");
        jButton2_Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_SimpanActionPerformed(evt);
            }
        });

        jButton3_Ubah.setText("Ubah");
        jButton3_Ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_UbahActionPerformed(evt);
            }
        });

        jButton4_Hapus.setText("Hapus");
        jButton4_Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_HapusActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1_Baru)
                        .addGap(52, 52, 52)
                        .addComponent(jButton2_Simpan)
                        .addGap(59, 59, 59)
                        .addComponent(jButton3_Ubah)
                        .addGap(66, 66, 66)
                        .addComponent(jButton4_Hapus)
                        .addGap(0, 136, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField5_Alamat)
                            .addComponent(jTextField4_Ttl)
                            .addComponent(jTextField3_JenisKelamin, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField2_Nama)
                            .addComponent(jTextField1_Nip)
                            .addComponent(jTextField6_Telf))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1_Nip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3_JenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4_Ttl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5_Alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jTextField6_Telf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1_Baru)
                    .addComponent(jButton2_Simpan)
                    .addComponent(jButton3_Ubah)
                    .addComponent(jButton4_Hapus))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2_NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2_NamaActionPerformed

    private void jTextField3_JenisKelaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3_JenisKelaminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3_JenisKelaminActionPerformed

    private void jTextField1_NipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_NipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_NipActionPerformed

    private void jTextField4_TtlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4_TtlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4_TtlActionPerformed

    private void jButton1_BaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_BaruActionPerformed
        // TODO add your handling code here:
        tombol(true);
        bersih();
    }//GEN-LAST:event_jButton1_BaruActionPerformed

    private void jButton2_SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_SimpanActionPerformed
        // TODO add your handling code here:
        try {
            koneksi.Koneksi.st.executeUpdate("insert into tbl_pegawai values ('" + jTextField1_Nip.getText() + "','" + jTextField2_Nama.getText() + "','" + jTextField3_JenisKelamin.getText() + "','" + jTextField4_Ttl.getText() + "','" + jTextField5_Alamat.getText() + "','" + jTextField6_Telf.getText() + "')");
            JOptionPane.showMessageDialog(null, "Berhasil menyimpan");
            tampilPengguna();
            tombol(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "eror Simpan : "+e);
        }//blok catch
    }//GEN-LAST:event_jButton2_SimpanActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if(jTable1.getSelectedColumnCount()==1){
            int row = jTable1.getSelectedRow();
            jTextField1_Nip.setText(jTable1.getValueAt(row, 0).toString());
            jTextField2_Nama.setText(jTable1.getValueAt(row, 1).toString());
            jTextField3_JenisKelamin.setText(jTable1.getValueAt(row, 2).toString());
            jTextField4_Ttl.setText(jTable1.getValueAt(row, 3).toString());
            jTextField5_Alamat.setText(jTable1.getValueAt(row, 4).toString());
            jTextField6_Telf.setText(jTable1.getValueAt(row, 5).toString());
            tombol(true);
        }//blok mause cliked
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4_HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_HapusActionPerformed
        // TODO add your handling code here:
        try {
            koneksi.Koneksi.st.executeUpdate("delete from tbl_pegawai where nip = '"+jTextField1_Nip.getText()+"' ");
            JOptionPane.showMessageDialog(null,"Berhasil menghapus ");
            tampilPengguna();
            tombol(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Eror Hapus : "+ e);
        }//blok hapus
    }//GEN-LAST:event_jButton4_HapusActionPerformed

    private void jButton3_UbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_UbahActionPerformed
        // TODO add your handling code here:
        try {
            koneksi.Koneksi.st.executeUpdate("update tbl_pegawai set nama='"+jTextField2_Nama.getText()+"', jenis_kelamin='"+jTextField3_JenisKelamin.getText()+"', ttl='"+jTextField4_Ttl.getText()+ "', alamat='"+ jTextField5_Alamat.getText() +"', telf='"+jTextField6_Telf.getText() +"' where nip = '"+jTextField1_Nip.getText()+"' ");
            JOptionPane.showMessageDialog(null,"Berhasil merubah ");
            tampilPengguna();
            tombol(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Eror Hapus : "+ e);
        }//blok Ubah

    }//GEN-LAST:event_jButton3_UbahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Pegawai dialog = new Pegawai(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1_Baru;
    private javax.swing.JButton jButton2_Simpan;
    private javax.swing.JButton jButton3_Ubah;
    private javax.swing.JButton jButton4_Hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1_Nip;
    private javax.swing.JTextField jTextField2_Nama;
    private javax.swing.JTextField jTextField3_JenisKelamin;
    private javax.swing.JTextField jTextField4_Ttl;
    private javax.swing.JTextField jTextField5_Alamat;
    private javax.swing.JTextField jTextField6_Telf;
    // End of variables declaration//GEN-END:variables
    void bersih(){
        jTextField1_Nip.setText("");
        jTextField2_Nama.setText(""); 
        jTextField3_JenisKelamin.setText(""); 
        jTextField4_Ttl.setText("");
        jTextField5_Alamat.setText("");
        jTextField6_Telf.setText("");
    }//ini blok bersih
    void tombol(boolean status){
        jButton1_Baru.setEnabled(true);
        jButton2_Simpan.setEnabled(status);
        jButton3_Ubah.setEnabled(status);
        jButton4_Hapus.setEnabled(status); 
    }//blok tombol
    private void headerTable(){
        model = new DefaultTableModel();
        model.addColumn("NIP");
        model.addColumn("Nama");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Tempat Tanggal Lahir"); 
        model.addColumn("Alamat"); 
        model.addColumn("Telf");
        jTable1.setModel(model);
    }//ini blok header
    public void tampilData (){
        model.getDataVector().removeAllElements();
        try {
            ResultSet rs=koneksi.Koneksi.st.executeQuery("SELECT * from view_pegawai");
            while(rs.next()){
                Object[] data = new Object[6];
                data[0]=(rs.getString(1));
                data[1]=(rs.getString(2));
                data[2]=(rs.getString(3));
                data[3]=(rs.getString(4));
                data[4]=(rs.getString(5));
                data[5]=(rs.getString(6));
//                data[6]=(rs.getString(7));
                model.addRow(data);
            }//ini tag while 
        } catch (Exception e) { 
            JOptionPane.showMessageDialog(null,"eror tampil : "+ e);
        } //ini tag catch
        bersih();
    }
    public void tampilPengguna(){
        model.getDataVector().removeAllElements();
        try {
            ResultSet rs=koneksi.Koneksi.st.executeQuery("select * from tbl_pegawai");
            while(rs.next()){
                Object[] data = new Object[6];
                data[0]=(rs.getString(1));
                data[1]=(rs.getString(2));
                data[2]=(rs.getString(3));
                data[3]=(rs.getString(4)); 
                data[4]=(rs.getString(5)); 
                data[5]=(rs.getString(6)); 
//                data[6]=(rs.getString(7));
                model.addRow(data);
            }//ini blok while 
        } catch (Exception e) { 
            JOptionPane.showMessageDialog(null,"eror tampil : "+ e);
        } //ini blok catch
        bersih();
    }//blok tampil
}
