/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package form;
import java.awt.Dimension;
import java.awt.Rectangle;
import java.awt.event.KeyEvent; 
import java.sql.Connection; 
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.Koneksi;

/**
 *
 * @author M ARIF MARTADINATA
 */
public class Pengguna extends javax.swing.JDialog {
        DefaultTableModel model = new DefaultTableModel();


    /**
     * Creates new form Pengguna
     */
    public Pengguna(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Koneksi.koneksi();
        headerTable();
        tampilData ();
        bersih();
        tombol(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1_ID = new javax.swing.JTextField();
        jTextField2_Nama = new javax.swing.JTextField();
        jTextField3_Password = new javax.swing.JTextField();
        jButton1_Baru = new javax.swing.JButton();
        jButton2_Simpan = new javax.swing.JButton();
        jButton3_Ubah = new javax.swing.JButton();
        jButton4_Hapus = new javax.swing.JButton();
        jButton5_Cetak = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jTextField1_Nip = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("ID ");

        jLabel2.setText("Nama :");

        jLabel3.setText("Password  : ");

        jTextField1_ID.setText("Masukan ID Anda");
        jTextField1_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_IDActionPerformed(evt);
            }
        });

        jTextField2_Nama.setText("Masukan Nama Anda");

        jTextField3_Password.setText("Masukan Password");
        jTextField3_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3_PasswordActionPerformed(evt);
            }
        });

        jButton1_Baru.setText("Baru");
        jButton1_Baru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_BaruActionPerformed(evt);
            }
        });

        jButton2_Simpan.setText("Simpan");
        jButton2_Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_SimpanActionPerformed(evt);
            }
        });

        jButton3_Ubah.setText("Ubah");
        jButton3_Ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_UbahActionPerformed(evt);
            }
        });

        jButton4_Hapus.setText("Hapus");
        jButton4_Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_HapusActionPerformed(evt);
            }
        });

        jButton5_Cetak.setText("Cetak");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel5.setText("NIP : ");

        jTextField1_Nip.setText("Masukan NIP Anda");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField2_Nama, javax.swing.GroupLayout.DEFAULT_SIZE, 1119, Short.MAX_VALUE)
                                    .addComponent(jTextField3_Password)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1_ID, javax.swing.GroupLayout.DEFAULT_SIZE, 1119, Short.MAX_VALUE)
                                    .addComponent(jTextField1_Nip))))
                        .addGap(0, 18, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1_Baru)
                .addGap(161, 161, 161)
                .addComponent(jButton2_Simpan)
                .addGap(222, 222, 222)
                .addComponent(jButton3_Ubah)
                .addGap(197, 197, 197)
                .addComponent(jButton4_Hapus)
                .addGap(137, 137, 137)
                .addComponent(jButton5_Cetak)
                .addContainerGap(196, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1_Nip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3)
                        .addGap(66, 66, 66))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField2_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jTextField3_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_Baru)
                    .addComponent(jButton2_Simpan)
                    .addComponent(jButton3_Ubah)
                    .addComponent(jButton4_Hapus)
                    .addComponent(jButton5_Cetak))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(288, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3_UbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_UbahActionPerformed
        // TODO add your handling code here:
         try {
            koneksi.Koneksi.st.executeUpdate("update tbl_pengguna set nama='"+jTextField2_Nama.getText()+"', password='"+jTextField3_Password.getText()+"' where nip = '"+jTextField1_ID.getText()+"' ");
            JOptionPane.showMessageDialog(null,"Berhasil merubah ");
            tampilPengguna();
            tombol(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Eror Hapus : "+ e);
        }//blok Ubah
    }//GEN-LAST:event_jButton3_UbahActionPerformed

    private void jButton1_BaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_BaruActionPerformed
        // TODO add your handling code here:
        tombol(true);
        bersih();
        
    }//GEN-LAST:event_jButton1_BaruActionPerformed

    private void jButton2_SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_SimpanActionPerformed
        // TODO add your handling code here:
        try {
            koneksi.Koneksi.st.executeUpdate("insert into tbl_pengguna values ('" + jTextField1_ID.getText() + "','" + jTextField1_Nip.getText() + "','" + jTextField2_Nama.getText() + "','" + jTextField3_Password.getText()  + "')");
            JOptionPane.showMessageDialog(null, "Berhasil menyimpan");
            tampilPengguna();
            tombol(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "eror Simpan : "+e);
        }//blok catch
        tampilData();
    }//GEN-LAST:event_jButton2_SimpanActionPerformed

    private void jButton4_HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_HapusActionPerformed
        // TODO add your handling code here:
        try {
            koneksi.Koneksi.st.executeUpdate("delete from tbl_pengguna where nip = '"+jTextField1_Nip.getText()+"' "); 
            JOptionPane.showMessageDialog(null, "Berhasil menghapus");
            tampilData();
            tombol(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "eror Hapus : "+e);
        }//blok catch
    }//GEN-LAST:event_jButton4_HapusActionPerformed

    private void jTextField1_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_IDActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         if(jTable1.getSelectedColumnCount()==1){
           int row = jTable1.getSelectedRow();
            jTextField1_ID.setText(jTable1.getValueAt(row, 0).toString());
            jTextField1_Nip.setText(jTable1.getValueAt(row, 1).toString());
            jTextField2_Nama.setText(jTable1.getValueAt(row, 2).toString());
            jTextField3_Password.setText(jTable1.getValueAt(row, 3).toString());
            
            tombol(true);
         }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField3_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3_PasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Pengguna dialog = new Pengguna(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_Baru;
    private javax.swing.JButton jButton2_Simpan;
    private javax.swing.JButton jButton3_Ubah;
    private javax.swing.JButton jButton4_Hapus;
    private javax.swing.JButton jButton5_Cetak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1_ID;
    private javax.swing.JTextField jTextField1_Nip;
    private javax.swing.JTextField jTextField2_Nama;
    private javax.swing.JTextField jTextField3_Password;
    // End of variables declaration//GEN-END:variables
    void bersih(){
        jTextField1_ID.setText("");
        jTextField1_Nip.setText("");
        jTextField2_Nama.setText(""); 
        jTextField3_Password.setText(""); 
        
    }
    private void headerTable(){
        model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("NIP");
        model.addColumn("Nama");
        model.addColumn("Password");
        
        jTable1.setModel(model);
    }//ini tag header
    public void tampilData (){
        model.getDataVector().removeAllElements();
        try {
            ResultSet rs=koneksi.Koneksi.st.executeQuery("SELECT * from view_pengguna");
            while(rs.next()){
                Object[] data = new Object[7];
                data[0]=(rs.getString(1));
                data[1]=(rs.getString(2));
                data[2]=(rs.getString(3));
                data[3]=(rs.getString(4));                
                data[4]=(rs.getString(5));  
                model.addRow(data);
            }//ini tag while 
        } catch (Exception e) { 
            JOptionPane.showMessageDialog(null,"eror tampil : "+ e);
        } //ini tag catch
        bersih();
    }
    void tombol(boolean status){
        jButton1_Baru.setEnabled(true);
        jButton2_Simpan.setEnabled(status);
        jButton3_Ubah.setEnabled(status);
        jButton4_Hapus.setEnabled(status);
        jButton5_Cetak.setEnabled(status);
 }//blok tombol
public void tampilPengguna(){
        model.getDataVector().removeAllElements();
        try {
            ResultSet rs=koneksi.Koneksi.st.executeQuery("select * from tbl_pengguna");
            while(rs.next()){
                Object[] data = new Object[6];
                data[0]=(rs.getString(1));
                data[1]=(rs.getString(2));
                data[2]=(rs.getString(3));
                data[3]=(rs.getString(4)); 
                data[4]=(rs.getString(5)); 
                model.addRow(data);
            }//ini blok while 
        } catch (Exception e) { 
            JOptionPane.showMessageDialog(null,"eror tampil : "+ e);
        } //ini blok catch
        bersih();
    }//blok tampil
}
